### ISSUE TITLE
Error in pest after installing pest-plugin-snapshots

### ISSUE THREAD

**Issue by itanea** [spatie/pest-plugin-snapshots#3]
On Windows 10 in Cmder via Laragon (PHP 7.4), I encounter this error when I ran ./bin/vendor/pest after I had installed pest-plugin-snapshots

![image](https://user-images.githubusercontent.com/425998/83578239-8c5ddc80-a536-11ea-98f9-635a8bfd449c.png)

It arrived with this pest's test :

![image](https://user-images.githubusercontent.com/425998/83578374-e6f73880-a536-11ea-9ac4-3a545e7a2658.png)

If I remove this pest's plugin, bug doesn't appear anymore.

**Comment by nunomaduro** [comment]
Thanks for reporting this issue, you can follow the progress here: https://github.com/pestphp/pest/issues/53.

**Comment by dimitrioskarvounaris** [comment]
This issue is one I encountered and is already fixed with #61, as soon it will be merged.
