### ISSUE TITLE
Ambiguous class resolution because of duplicated traits

### ISSUE THREAD

**Issue by Gummibeer** [spatie/pest-plugin-snapshots#6]
> Warning: Ambiguous class resolution, "Spatie\Snapshots\Concerns\SnapshotDirectoryAware" was found 2x: in "vendor/spatie/pest-plugin-snapshots/src/Concerns/SnapshotDirectoryAware.php" and "vendor/spatie/phpunit-snapshot-assertions/src/Concerns/SnapshotDirectoryAware.php", the first will be used.

> Warning: Ambiguous class resolution, "Spatie\Snapshots\Concerns\SnapshotIdAware" was found 2x: in "vendor/spatie/pest-plugin-snapshots/src/Concerns/SnapshotIdAware.php" and "vendor/spatie/phpunit-snapshot-assertions/src/Concerns/SnapshotIdAware.php", the first will be used.

Are these trait duplicates needed for anything? If so I think that this package should use [exclude-files-from-classmaps](https://getcomposer.org/doc/04-schema.md#exclude-files-from-classmaps) to exclude the original files and load the overrides.

**Comment by nunomaduro** [comment]
Thanks for creating this issue. Can you create a pull request with your idea?
